image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  # Сначала устанавливаем зависимости и проверяем сборку
  - ./gradlew assemble

test_script:
  # Запускаем тесты
  - ./gradlew test --info